apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
  namespace: app
spec:
  ports:
  - name: omarport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: omarapp
  type: LoadBalancer
status:
  loadBalancer: {}